# Generated by Django 4.1.5 on 2023-01-07 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='City',
            new_name='Branch',
        ),
        migrations.RenameModel(
            old_name='Country',
            new_name='District',
        ),
        migrations.RenameField(
            model_name='branch',
            old_name='country',
            new_name='district',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='city',
            new_name='branch',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='country',
            new_name='district',
        ),
    ]
